spring:
  application:
    name: demo
  datasource:  
    url: jdbc:postgresql://192.168.56.104:5432/mydb?useSSL=false
    username: user1  
    password: Baumkuchen


jpa:
  hibernate:
    ddl-auto: none  # Добавить столбцы из сущности
  show-sql: true  # Выводить SQL в логи


server:
  port: 8080
